/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'graphbit.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./graphbit.android-arm64.node')
          } else {
            nativeBinding = require('graphbit-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'graphbit.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./graphbit.android-arm-eabi.node')
          } else {
            nativeBinding = require('graphbit-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'graphbit.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./graphbit.win32-x64-msvc.node')
          } else {
            nativeBinding = require('graphbit-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'graphbit.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./graphbit.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('graphbit-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'graphbit.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./graphbit.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('graphbit-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'graphbit.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./graphbit.darwin-universal.node')
      } else {
        nativeBinding = require('graphbit-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'graphbit.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./graphbit.darwin-x64.node')
          } else {
            nativeBinding = require('graphbit-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'graphbit.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./graphbit.darwin-arm64.node')
          } else {
            nativeBinding = require('graphbit-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'graphbit.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./graphbit.freebsd-x64.node')
      } else {
        nativeBinding = require('graphbit-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'graphbit.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./graphbit.linux-x64-musl.node')
            } else {
              nativeBinding = require('graphbit-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'graphbit.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./graphbit.linux-x64-gnu.node')
            } else {
              nativeBinding = require('graphbit-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'graphbit.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./graphbit.linux-arm64-musl.node')
            } else {
              nativeBinding = require('graphbit-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'graphbit.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./graphbit.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('graphbit-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'graphbit.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./graphbit.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('graphbit-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'graphbit.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./graphbit.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('graphbit-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'graphbit.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./graphbit.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('graphbit-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'graphbit.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./graphbit.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('graphbit-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'graphbit.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./graphbit.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('graphbit-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { DocumentLoaderConfig, DocumentLoader, EmbeddingClient, EmbeddingConfig, LlmClient, LlmConfig, CharacterSplitter, TokenSplitter, SentenceSplitter, RecursiveSplitter, WorkflowContext, Executor, Node, WorkflowResult, Workflow, init, version, getSystemInfo, healthCheck, configureRuntime, shutdown } = nativeBinding

module.exports.DocumentLoaderConfig = DocumentLoaderConfig
module.exports.DocumentLoader = DocumentLoader
module.exports.EmbeddingClient = EmbeddingClient
module.exports.EmbeddingConfig = EmbeddingConfig
module.exports.LlmClient = LlmClient
module.exports.LlmConfig = LlmConfig
module.exports.CharacterSplitter = CharacterSplitter
module.exports.TokenSplitter = TokenSplitter
module.exports.SentenceSplitter = SentenceSplitter
module.exports.RecursiveSplitter = RecursiveSplitter
module.exports.WorkflowContext = WorkflowContext
module.exports.Executor = Executor
module.exports.Node = Node
module.exports.WorkflowResult = WorkflowResult
module.exports.Workflow = Workflow
module.exports.init = init
module.exports.version = version
module.exports.getSystemInfo = getSystemInfo
module.exports.healthCheck = healthCheck
module.exports.configureRuntime = configureRuntime
module.exports.shutdown = shutdown
